=== okosyk/aion_server/game/data/static_data/items/skill_enchants.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../modifiers.xsd"/>
	<xs:element name="skill_enchants">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="skill_enchant" type="SkillEnchantTemplate" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="SkillEnchantTemplate">
		<xs:sequence>
			<xs:element name="modifiers" type="Modifiers" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:sequence>
			<xs:element name="skill" type="SkillTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="SkillTemplate">
		<xs:attribute name="id" type="xs:int" use="required"/>
	</xs:complexType>
</xs:schema>

=== okosyk/aion_server/game/data/static_data/items/skill_enchants.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
	Skill Enchant 5.0/5.1/5.3
	Made By Encom
 -->
<skill_enchants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="skill_enchants.xsd">
    <skill_enchant id="1">
        <modifiers chance="5.0">
           <skill id="784"/>
        </modifiers>
		<modifiers chance="3.0">
           <skill id="826"/>
        </modifiers>
		<modifiers chance="2.0">
           <skill id="830"/>
        </modifiers>
    </skill_enchant>
    <skill_enchant id="2">
        <modifiers chance="5.0">
           <skill id="784"/>
        </modifiers>
    </skill_enchant>
    <skill_enchant id="3">
	    <modifiers chance="10.0">
           <skill id="1282"/>
        </modifiers>
    </skill_enchant>
    <skill_enchant id="4">
	    <modifiers chance="10.0">
           <skill id="1282"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="5">
	    <modifiers chance="10.0">
           <skill id="1282"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="6">
	    <modifiers chance="10.0">
           <skill id="508"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="7">
	    <modifiers chance="10.0">
           <skill id="682"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="8">
	    <modifiers chance="10.0">
           <skill id="621"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="9">
	    <modifiers chance="10.0">
           <skill id="554"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="10">
	    <modifiers chance="10.0">
           <skill id="545"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="11">
	    <modifiers chance="10.0">
           <skill id="3031"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="12">
	    <modifiers chance="10.0">
           <skill id="3106"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="13">
	    <modifiers chance="10.0">
           <skill id="2967"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="14">
	    <modifiers chance="10.0">
           <skill id="3162"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="15">
	    <modifiers chance="10.0">
           <skill id="3069"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="16">
	    <modifiers chance="10.0">
           <skill id="3356"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="17">
	    <modifiers chance="10.0">
           <skill id="3404"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="18">
	    <modifiers chance="10.0">
           <skill id="3455"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="19">
	    <modifiers chance="10.0">
           <skill id="3300"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="20">
	    <modifiers chance="10.0">
           <skill id="3406"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="21">
	    <modifiers chance="10.0">
           <skill id="848"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="22">
	    <modifiers chance="10.0">
           <skill id="1086"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="23">
	    <modifiers chance="10.0">
           <skill id="1054"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="24">
	    <modifiers chance="10.0">
           <skill id="1090"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="25">
	    <modifiers chance="10.0">
           <skill id="1120"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="26">
	    <modifiers chance="10.0">
           <skill id="3867"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="27">
	    <modifiers chance="10.0">
           <skill id="4098"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="28">
	    <modifiers chance="10.0">
           <skill id="3939"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="29">
	    <modifiers chance="10.0">
           <skill id="3912"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="30">
	    <modifiers chance="10.0">
           <skill id="3918"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="31">
	    <modifiers chance="10.0">
           <skill id="1562"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="32">
	    <modifiers chance="10.0">
           <skill id="1735"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="33">
	    <modifiers chance="10.0">
           <skill id="1715"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="34">
	    <modifiers chance="10.0">
           <skill id="1557"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="35">
	    <modifiers chance="10.0">
           <skill id="1798"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="36">
	    <modifiers chance="10.0">
           <skill id="1506"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="37">
	    <modifiers chance="10.0">
           <skill id="1192"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="38">
	    <modifiers chance="10.0">
           <skill id="1421"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="39">
	    <modifiers chance="10.0">
           <skill id="1384"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="40">
	    <modifiers chance="10.0">
           <skill id="1543"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="41">
	    <modifiers chance="10.0">
           <skill id="3643"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="42">
	    <modifiers chance="10.0">
           <skill id="3852"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="43">
	    <modifiers chance="10.0">
           <skill id="3630"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="44">
	    <modifiers chance="10.0">
           <skill id="3839"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="45">
	    <modifiers chance="10.0">
           <skill id="3838"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="46">
	    <modifiers chance="10.0">
           <skill id="1995"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="47">
	    <modifiers chance="10.0">
           <skill id="2350"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="48">
	    <modifiers chance="10.0">
           <skill id="2041"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="49">
	    <modifiers chance="10.0">
           <skill id="2204"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="50">
	    <modifiers chance="10.0">
           <skill id="2264"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="51">
	    <modifiers chance="10.0">
           <skill id="4400"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="52">
	    <modifiers chance="10.0">
           <skill id="4368"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="53">
	    <modifiers chance="10.0">
           <skill id="4392"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="54">
	    <modifiers chance="10.0">
           <skill id="4396"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="55">
	    <modifiers chance="10.0">
           <skill id="4297"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="56">
	    <modifiers chance="10.0">
           <skill id="2568"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="57">
	    <modifiers chance="10.0">
           <skill id="2756"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="58">
	    <modifiers chance="10.0">
           <skill id="4647"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="59">
	    <modifiers chance="10.0">
           <skill id="2717"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="60">
	    <modifiers chance="10.0">
           <skill id="2726"/>
        </modifiers>
    </skill_enchant>
	<!-- 5.0 -->
	<skill_enchant id="61">
	    <modifiers chance="1.43">
		    <skill id="3140"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="3084"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="2864"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="2877"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="3055"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="3113"/>
        </modifiers>
	    <modifiers chance="1.42">
		    <skill id="3065"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="62">
	    <modifiers chance="1.43">
		    <skill id="3140"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="3084"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="2864"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="2877"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="3055"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="3113"/>
        </modifiers>
	    <modifiers chance="1.42">
		    <skill id="3065"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="63">
	    <modifiers chance="1.43">
		    <skill id="1768"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="1769"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="1700"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="1580"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="1858"/>
        </modifiers>
	    <modifiers chance="1.43">
		    <skill id="4012"/>
        </modifiers>
	    <modifiers chance="1.42">
		    <skill id="4685"/>
        </modifiers>
    </skill_enchant>
	<skill_enchant id="64">
        <skill id="3223"/>
	    <modifiers chance="7.2">
        </modifiers>
        <skill id="3365"/>
	    <modifiers chance="7.2">
